### ISSUE TITLE
Parse is not defined

### ISSUE THREAD

**Issue by syampsijk** [willdages/CodeMashQuotes-Demo#1]
Reports error 
Parse is not defined
Please fill in your own Parse.com App ID and Javascript Key on line 107 of index.html
.But i have already initialized with application key and javascript  key

**Comment by willdages** [comment]
Hi @syampsijk, you mentioned in the YouTube comment this morning that you figured out the problem. Can you let me know what it was, and if there's anything I can do to clarify in the tutorial or help others avoid the same problem? Thanks!

**Comment by syampsijk** [comment]
Its okay now.actually there was another parse.initialize in it thats why it created error.anyway nice tutorial
